<div class="content">
    <?php View::content(); ?>
    <h3>Menus</h3>
    <ul>
        <?php foreach ($listMenus->items as $item) : ?>
            <li>
                <?php echo Html::linkAction("edit/$item->id/", 'Editar') ?>
                <?php echo Html::linkAction("del/$item->id/", 'Borrar') ?>
                <strong><?php echo $item->nombre ?> - <?php echo $item->titulo ?></strong>
            </li>
        <?php endforeach; ?>
    </ul>

    
    <?php if ($listMenus->prev) echo Html::linkAction("index/$listMenus->prev/", '<< Anterior |'); ?>
    <?php if ($listMenus->next) echo Html::linkAction("index/$listMenus->next/", 'Próximo >>'); ?>
</div>
