<?php 
$ar = array('Abdomen' => 'Abdomen',
            'Brazos' => 'Brazos',
            'Cabeza' => 'Cabeza',
            'Cuello' => 'Cuello',
            'Genitales' => 'Genitales',
            'Piernas' => 'Piernas',
            'Tórax' => 'Tórax',
            'Otros' => 'Otros'); 
?>	
<div id='logo-kumbia'><?php echo Html::img('site_logo.gif','KumbiaPHP logo',array('id' => 'loguito','class'=>'logo','title' => 'Mi foto')) ?></div>
        <div>
            <?php echo html::lists($ar, 'ul','style="margin-left:20px;padding-left:20px"') ?>
        </div>
    <div id='info'>
		<h1>KumbiaPHP está listo para usarse</h1>
        <p><strong>Bienvenido a KumbiaPHP Framework</strong>. El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente
       , sin tener que reinventar la rueda, y preocupandose por lo más importante, la lógica de su aplicación.</p>
         <h2>Como empezar</h2>
        <p>En nuestra <a href="http://wiki.kumbiaphp.com/">wiki</a> podrás encontrar información actualizada sobre el uso del framework,
        si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
        <strong><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>
        tambien puede interesarte saber sobre:</p>
		<ul>
			<li><h3><a href="http://wiki.kumbiaphp.com/Beta2_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></h3></li>
			<li><h3><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></h3></li>
			<li><h3><a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">Configurar conexiones a bases de datos</a></h3></li>
		</ul>
		<p>Estos son solo algunos ejemplos puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p>
    </div>
