<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $titulo ?></title>

    <!-- Bootstrap core CSS -->
    <?php Tag::css('sbadmin/bootstrap') ?>

    <!-- Add custom CSS here -->
    <?php Tag::css('sbadmin/sb-admin') ?>
    <?php Tag::css('sbadmin/font-awesome/css/font-awesome.min') ?>

    <?php echo Html::includeCss() ?>
    <!-- Page Specific CSS -->
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
    
    
  </head>
  
  <body>

      <div id="wrapper">
          Probando
      </div>
  </body>